tap "aquaproj/aqua"
tap "idoavrah/homebrew"
tap "yukiarrr/tap"

brew "aqua"
brew "awscli"
brew "direnv"
brew "ecsk"
brew "fastlane"
brew "gemini-cli"
brew "gh"
brew "git"
brew "mas"
brew "mise"
brew "nodebrew"
brew "php"
brew "tftui"
brew "tfenv"
brew "tflint"
brew "tfmigrate"
brew "tgenv"
brew "tree"
brew "trivy"
brew "uv"
brew "xcodegen"
brew "xcode-build-server"

cask "alfred"
# cask "kiro-cli" # 既にインストール済みだとエラーになるためコメントアウト
cask "appcleaner"
cask "claude-code"
cask "codex"
cask "discord"
cask "docker-desktop"
cask "figma"
cask "google-chrome"
cask "google-drive"
cask "jordanbaird-ice@beta"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "menubarx"
cask "notchnook"
cask "postman"
cask "readdle-spark"
# cask "sequel-ace"
cask "shottr"
cask "slack"
cask "vrew"
cask "visual-studio-code"
cask "zoom"

# font
cask "font-noto-sans-jp"
cask "font-zen-kaku-gothic-new"
